version: "3.8"

services:
    app:
        container_name: app
        image: app_image
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
